"""Add Column to user database, that stores if they want to enable community custom css

Revision ID: 0526e322b9f4
Revises: bfe38d537d3d
Create Date: 2026-03-28 10:33:47.998896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0526e322b9f4'
down_revision = 'bfe38d537d3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('allow_community_css', sa.Boolean(), server_default=sa.text('TRUE'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('allow_community_css')

    # ### end Alembic commands ###
