"""Add option for admins to disable em dash filter

Revision ID: 404298db0866
Revises: f26c13621774
Create Date: 2026-01-31 22:53:32.224850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '404298db0866'
down_revision = 'f26c13621774'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enable_report_em_dash_replies', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site', schema=None) as batch_op:
        batch_op.drop_column('enable_report_em_dash_replies')

    # ### end Alembic commands ###
