"""Add option to disable em dash detector

Revision ID: 76352da7ff96
Revises: 7524920417ef
Create Date: 2026-01-30 22:32:34.143608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76352da7ff96'
down_revision = '7524920417ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enable_em_dash_reply_filter', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site', schema=None) as batch_op:
        batch_op.drop_column('enable_em_dash_reply_filter')

    # ### end Alembic commands ###
