"""Added a column to store additional css for a Community

Revision ID: bfe38d537d3d
Revises: 336345ec53d0
Create Date: 2026-03-27 16:46:55.688546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfe38d537d3d'
down_revision = '336345ec53d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('community', schema=None) as batch_op:
        batch_op.add_column(sa.Column('additional_css', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('community', schema=None) as batch_op:
        batch_op.drop_column('additional_css')

    # ### end Alembic commands ###
